name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install markdown

      - name: Generate HTML and Read Markdown
        run: |
          python src/CriarMarkdown.py
          python src/lerMarkdown.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Generating Pages for Blog"
          git push origin main
